---
title: "analysis"
author: "Eden Deng, Jane Zhang, Shari Tian"
date: "11/6/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning = FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(foreign)
library(naniar)
library(mlmi)
library(glmnet)
```

```{r warning = FALSE}
wave1 <- read.spss("dataset2021/data/data/W1 Merged Data/Wave.1_Data/Merge/Wave1_20170906.sav", 
                  to.data.frame=TRUE)
```

```{r warning = FALSE}
wave2 <- read.spss("dataset2021/data/data/W2 Merged Data/2w-3rd_release_all/merge/Wave2_20170724.sav", 
                  to.data.frame=TRUE)
```

```{r imputation}
# Country data
mainland <- read.csv("cleaned_data/Mainland China_data.csv")
hongkong <- read.csv("cleaned_data/Hong Kong_data.csv")
korea <- read.csv("cleaned_data/Korea_data.csv")
japan <- read.csv("cleaned_data/Japan_data.csv")
philippines <- read.csv("cleaned_data/Philippines_data.csv")
taiwan <- read.csv("cleaned_data/Taiwan_data.csv")
thailand <- read.csv("cleaned_data/Thailand_data.csv")

mainland <- mainland %>%
  select(-c("name", "country", "X"))
hongkong <- hongkong %>%
  select(-c("name", "country", "X"))
korea <- korea %>%
  select(-c("name", "country", "X"))
japan <- japan %>%
  select(-c("name", "country", "X"))
philippines <- philippines %>%
  select(-c("name", "country", "X"))
taiwan <- taiwan %>%
  select(-c("name", "country", "X"))
thailand <- thailand %>%
  select(-c("name", "country", "X"))

# Visualize missing values
vis_miss(mainland)
miss_var_summary(mainland)
pct_miss(mainland)

miss_var_summary(korea)
pct_miss(korea)

pct_miss(japan)

pct_miss(thailand)

# test MCAR
mcar_test(mainland)
mcar_test(hongkong)
mcar_test(korea) # not MCAR at alpha = 0.05
mcar_test(japan) # not MCAR at alpha = 0.05
mcar_test(philippines)
mcar_test(taiwan)
mcar_test(thailand) # not MCAR at alpha = 0.05
  
# Categorical imputation using saturated log-linear models, MCMC
mainland_impute <- catImp(mainland, M=1, pd=TRUE, type=3, rseed=4423)
names(mainland_impute) <- names(mainland)
write.csv(mainland_impute, "imputed_data/mainland_china_imputed.csv")

hongkong_impute <- catImp(hongkong, M=1, pd=TRUE, type=3, rseed=4423)
names(hongkong_impute) <- names(hongkong)
write.csv(hongkong_impute, "imputed_data/hongkong_imputed.csv")

korea_impute <- catImp(korea, M=1, pd=TRUE, type=3, rseed=4423)
names(korea_impute) <- names(korea)
write.csv(korea_impute, "imputed_data/korea_imputed.csv")

japan_impute <- catImp(japan, M=1, pd=TRUE, type=3, rseed=4423)
names(japan_impute) <- names(japan)
write.csv(japan_impute, "imputed_data/japan_imputed.csv")

philippines_impute <- catImp(philippines, M=1, pd=TRUE, type=3, rseed=4423)
names(philippines_impute) <- names(philippines)
write.csv(philippines_impute, "imputed_data/philippines_imputed.csv")

taiwan_impute <- catImp(taiwan, M=1, pd=TRUE, type=3, rseed=4423)
names(taiwan_impute) <- names(taiwan)
write.csv(taiwan_impute, "imputed_data/taiwan_imputed.csv")

thailand_impute <- catImp(thailand, M=1, pd=TRUE, type=3, rseed=4423)
names(thailand_impute) <- names(thailand)
write.csv(thailand_impute, "imputed_data/thailand_imputed.csv")
```

```{r probit-frequentist}
lm(binomial(link = "probit"))
```


```{r probit-bayes}
if(nchar(Sys.getenv("LONG_TEST")) != 0) {R=2000} else {R=10}
set.seed(66)

# probit bayes model
data1 = list(X=mainland, y=simout$y)
mcmc1 = list(R=R, keep=1)

out = rbprobitGibbs(Data=Data1, Mcmc=Mcmc1)
summary(out$betadraw, tvalues=beta)

## plotting example
if(0){plot(out$betadraw, tvalues=beta)}

```

