---
title: "analysis_2"
author: "Eden Deng, Jane Zhang, Shari Tian"
date: "11/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Packages

```{r load_data, warning = FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(foreign)
library(naniar)
library(mlmi)
library(glmnet)
library(bayesm)

```

# Load Data

```{r}

taiwan_orig <- read.csv("probit_taiwan_data.csv")
taiwan_orig <- taiwan_orig %>%
  select(-X)
```

# Data Imputation

```{r impute}
miss_var_summary(taiwan_orig)

pct_miss(taiwan_orig)

vis_miss(taiwan_orig)

mcar_test(taiwan_orig)

#taiwan_impute <- catImp(taiwan_orig, M=1, pd=TRUE, steps = 500, type=3, rseed=4423)
#names(taiwan_impute) <- names(taiwan_orig)

# rename variables
# taiwan <- data.frame("Gender" = factor(taiwan_impute$se002, ordered = TRUE), "Age" = factor(taiwan_impute$se003, ordered = TRUE), "Education" = factor(taiwan_impute$se005, ordered = TRUE), "Income" = factor(taiwan_impute$se009, ordered = TRUE), "PolInterest" = factor(taiwan_impute$q056, ordered = TRUE), "DemSat" = factor(taiwan_impute$q098, ordered = TRUE), "Vote" = factor(taiwan_impute$q027, ordered = TRUE), "UnderstandPol" = factor(taiwan_impute$q127, ordered = TRUE), "TrustGov" = factor(taiwan_impute$q131, ordered = TRUE))

#write.table(taiwan, "probit_taiwan_imputed.dat")

taiwan <- read.table("probit_taiwan_imputed.dat")

# factor variables
taiwan[colnames(taiwan)] <- lapply(taiwan[colnames(taiwan)], factor)
```

# Probit Regression Model

```{r}
model <- glm(Vote ~ ., family = binomial(link = "probit"), 
    data = taiwan)

summary(model)
```

# Bayesian Probit

```{r}
y <- c(taiwan$Vote)
y <- replace(y, y == 1, 0)
y <- replace(y, y == 2, 1)
```


```{r}
gender <- c(taiwan$Gender)
age <- c(taiwan$Age)
education <- c(taiwan$Education)
income <- c(taiwan$Income)
polinterest <- c(taiwan$PolInterest)
demsat <- c(taiwan$DemSat)
understandpol <- c(taiwan$UnderstandPol)
trustgov <- c(taiwan$TrustGov)
```

```{r}
X<-cbind(gender,age,education, income,polinterest,demsat,understandpol,trustgov)
betabar <- rep(0, nrow(X))
A <- (1/nrow(X))*t(X)%*%X
R <- 10000
keep <- 1
nprint <- 0
```

```{r}
Data <- list(y=y, X=X)
Prior <- list(A=A)
Mcmc <- list(R=R, keep=keep, nprint=nprint)
```


```{r}
out <- rbprobitGibbs(Data, Prior, Mcmc)
```

```{r}
betas <- out$betadraw
```

# Density Plots

```{r}
ci_b2 <- quantile(betas[,2], c(0.025, 0.975))
ggdensity(betas[,2], title = "Density of Coefficient for Age", xlab = FALSE, fill = "lightgray",
   add = "mean", rug = TRUE) +
  geom_vline(xintercept = ci_b2[1], linetype = "dashed", color = "red") +
  geom_vline(xintercept = ci_b2[2], linetype = "dashed", color = "red")
```
```{r}
ci_b4 <- quantile(betas[,4], c(0.025, 0.975))
ggdensity(betas[,4], title = "Density of Coefficient for Income", xlab = FALSE, fill = "lightgray",
   add = "mean", rug = TRUE) +
  geom_vline(xintercept = ci_b4[1], linetype = "dashed", color = "red") +
  geom_vline(xintercept = ci_b4[2], linetype = "dashed", color = "red")
```

```{r}
ci_b5 <- quantile(betas[,5], c(0.025, 0.975))
ggdensity(betas[,5], title = "Density of Coefficient for Political Interest", xlab = FALSE, fill = "lightgray",
   add = "mean", rug = TRUE) +
  geom_vline(xintercept = ci_b5[1], linetype = "dashed", color = "red") +
  geom_vline(xintercept = ci_b5[2], linetype = "dashed", color = "red")

```

# Final Selected Model

```{r}
step(model, scope = list(upper =~., lower =~1), k = log(nrow(taiwan)), direction = "both")
```


```{r}
# wave2 <- read.spss("dataset2021/data/data/W2 Merged Data/2w-3rd_release_all/merge/Wave2_20170724.sav", 
#                   to.data.frame=TRUE)
# 
# taiwan2 <- wave2 %>%
#   filter(country=="Taiwan") %>%
#   select(se3a, q49, q38)
# 
# taiwan2$se3a <- as.numeric(taiwan2$se3a)
# 
# taiwan2$Age <- cut(taiwan2$se3a, breaks = c(0,25,30,35,40,45,50,55,60,71,76,Inf), right=FALSE, labels=c(2:12))
# 
# taiwan2 <- taiwan2 %>% select(-se3a)
# 
# taiwan2 <- taiwan2 %>% replace_with_na(replace = list(q38 = c("Not applicable", "No answer", "Can't choose", "Decline to answer")))
# 
# taiwan2 <- taiwan2 %>% replace_with_na(replace = list(q49 = c("No answer", "Can't choose", "Decline to answer")))
# 
# taiwan2x <- na.omit(taiwan2)
# 
# names(taiwan2x) <- c("PolInterest", "Vote", "Age")
# 
# taiwan2x$PolInterest <- factor(as.numeric(taiwan2x$PolInterest), ordered = TRUE)
# taiwan2x$Age <- factor(taiwan2x$Age, ordered = TRUE)
# 
# taiwan2x$Vote[taiwan2x$Vote == "Yes"] <- "2"
# taiwan2$Vote[taiwan2$Vote == "No"] <- "1"
```

```{r performance_eval}
taiwan2 <- read.csv("taiwan_data_w2.csv")
taiwan2 <- taiwan2 %>% select(-X)
names(taiwan2) <- c("Vote", "PolInterest", "Age")
taiwan2$Age <- factor(taiwan2$Age, ordered = TRUE)
taiwan2$Vote <- factor(taiwan2$Vote, ordered = TRUE)
taiwan2$PolInterest <- factor(taiwan2$PolInterest, ordered = TRUE)

<<<<<<< HEAD
=======
taiwan2 <- wave2 %>%
  filter(country=="Taiwan") %>%
  select(se3a, q49, q38)

taiwan2$se3a <- as.numeric(taiwan2$se3a)

taiwan2$Age <- cut(taiwan2$se3a, breaks = c(0,25,30,35,40,45,50,55,60,71,76,Inf), right=FALSE, labels=c(2:12))

taiwan2 <- taiwan2 %>% select(-se3a)

taiwan2 <- taiwan2 %>% replace_with_na(replace = list(q38 = c("Not applicable", "No answer", "Can't choose", "Decline to answer")))

taiwan2 <- taiwan2 %>% replace_with_na(replace = list(q49 = c("No answer", "Can't choose", "Decline to answer")))

taiwan2 <- na.omit(taiwan2)

names(taiwan2) <- c("PolInterest", "Vote", "Age")

taiwan2$PolInterest <- factor(as.numeric(taiwan2$PolInterest), ordered = TRUE)
taiwan2$Age <- factor(taiwan2$Age, ordered = TRUE)

#taiwan2$Vote[taiwan2$Vote == "Yes"] <- "2"
#taiwan2$Vote[taiwan2$Vote == "No"] <- "1"

Vote <- c(taiwan2$Vote)
Vote <- replace(vote, vote == "Yes", "2")
Vote <- replace(vote, vote == "No", "1")
Vote <- factor(Vote, ordered = TRUE)

taiwan2 <- taiwan2 %>% select(-Vote)
taiwan2 <- cbind(taiwan2, Vote)
```

```{r}
final_model <- glm(Vote ~ PolInterest + Age, family = binomial(link = "probit"), 
    data = taiwan)

X <- taiwan2 %>%
  select(-Vote)

Yhat <- predict(final_model, newdata = X,
            type = "response")

library(pROC)
library(InformationValue)
optCutOff <- optimalCutoff(taiwan2$Vote, Yhat)[1]
test_roc = roc(taiwan2$Vote ~ Yhat, plot = TRUE, print.auc = TRUE)
thresh <- coords(test_roc, "best")['threshold']

model_pred <- cut(Yhat, breaks = c(-Inf,thresh,Inf), right=FALSE, labels=c(1:2))

train_tab = table(predicted = model_pred, actual = taiwan2$Vote)
library(caret)
train_con_mat = caret::confusionMatrix(train_tab, positive = "2")
c(train_con_mat$overall["Accuracy"], 
  train_con_mat$byClass["Sensitivity"], 
  train_con_mat$byClass["Specificity"])

# plot
library(cvms)
tib <- tibble("target" = taiwan2$Vote,
                     "prediction" = model_pred)

basic_table <- table(tib)
cfm <- as_tibble(basic_table)
plot_confusion_matrix(cfm, 
                      target_col = "target", 
                      prediction_col = "prediction",
                      counts_col = "n")
```

